version: '3.8'

services:
  krefasy-backoffice:
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs:/var/log/nginx
    restart: unless-stopped
    networks:
      - krefasy-network

  # Redis para cache e sessões (opcional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - krefasy-network

  # Nginx reverso (opcional)
  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - krefasy-backoffice
    restart: unless-stopped
    networks:
      - krefasy-network

volumes:
  redis-data:

networks:
  krefasy-network:
    driver: bridge
